name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-26, macos-26-intel]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-release
          path: target/release/
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
